### ISSUE TITLE
Step 'Hoe heet je?' (what is your name?) has different positions for labels, last name (achternaam is focused

### ISSUE THREAD

**Issue by pdj-eu** [I-OWE-YOU/web-frontend#15]
![File (2)](https://user-images.githubusercontent.com/62385123/77110976-c125c180-6a26-11ea-89c9-53a867b7903f.jpg)

'Hoe heet je?' stap - labels verschillend

**Comment by mmeester** [comment]
I've fixed the focus issue in PR #20

**Comment by mmeester** [comment]
Alignment is fixed in the same PR
