### ISSUE TITLE
Current page tegoedje.nu has no content at all

### ISSUE THREAD

**Issue by rianrietveld** [I-OWE-YOU/web-frontend#23]
The current page tegoedje.nu doesn't contain any content other than what's visually on the background image.

I propose to add text, hidden from screen, but announced by screen readers, so blind visitors also have an idea what this page is about. Adding the CSS can be handy in the rest of the pages to give more context to blind users on what's happening. I can address this in issues later.

For the there is the css (the class name is optional, I don't know if there is an equivalent in Vue):

**CSS**
```
.screen-reader-text {
  border: 0;
  clip: rect(1px, 1px, 1px, 1px);
  clip-path: inset(50%);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
  word-wrap: normal !important;
}
```

**HTML**
```
<h1 class="screen-reader-text">Tegoedje.nu</h1>
<p class="screen-reader-text">Voor nu, voor straks.</p>
<p class="screen-reader-text">Deze website gaat binnenkort online.</p>
```

**Explanation of the CSS is on:**
https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/

**Note:** display: none; and visibility: hidden; hide text from screen, but also for a screen reader, so they can’t be used to give extra information to screen reader users.

**Comment by jeroensmeets** [comment]
Thx, used your info to create a new temp page.
