### ISSUE TITLE
Address interferes with email input screen

### ISSUE THREAD

**Issue by pdj-eu** [I-OWE-YOU/web-frontend#27]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/62385123/77175034-45795280-6ac2-11ea-882c-d2008d4e54dd.png">

The address is shown in the enail input screen. It popped up while typing my emailadres.

**Comment by IAfanasovMob** [comment]
I believe it is fixed. I saw the code that could have fixed it. Tested manually and did not reproduce it.
@pdj-eu are you comfortable closing this issue?

**Comment by pdj-eu** [comment]
I have tested it again. Couldn’t reproduce it anymore. So it seems fixed.
Thanks.

**Comment by IAfanasovMob** [comment]
not reproducible anymore
