### ISSUE TITLE
Postal code check 'always' returns a known address, also when the format of the postal code is incorrect

### ISSUE THREAD

**Issue by pdj-eu** [I-OWE-YOU/web-frontend#29]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/62385123/77175841-82921480-6ac3-11ea-86b1-d910c82f99f8.png">

Postal code check 'always' returns a known address, also when the format of the postal code is incorrect.

**Comment by jeroensmeets** [comment]
@pdj-eu woudl you like to see a check in the frontend, or should the API be more strict?

**Comment by pdj-eu** [comment]
a check in the front end would be ok.

**Comment by jeroensmeets** [comment]
Fixed by https://github.com/I-OWE-YOU/web-frontend/pull/37
