### ISSUE TITLE
change "KvK nummer" inputmode to "numeric"

### ISSUE THREAD

**Issue by IAfanasovMob** [I-OWE-YOU/web-frontend#43]
According to [kvk.nl](https://www.kvk.nl/advies-en-informatie/bedrijf-starten/kvk-nummer-alles-wat-je-moet-weten/) it is 8-digit number. inputmode="numeric" guides a mobile phone to show a special keyboard with numbers only.

**Comment by jeroensmeets** [comment]
In Vue, it can be done by leaving out the input type, and using `v-model.number`, see

https://vuejs.org/v2/guide/forms.html#number

**Comment by IAfanasovMob** [comment]
Sorry, I confused a bit here.
What I meant is actually `inputmode="numeric"`. Updated the first message.
