### ISSUE TITLE
Tikkie URL instruction a "Sluiten" button at the bottom instead of a "X" on the to

### ISSUE THREAD

**Issue by IAfanasovMob** [I-OWE-YOU/web-frontend#60]
![instruction](https://user-images.githubusercontent.com/44999963/77515420-cd6fab80-6e78-11ea-8279-a7cc7d4b378b.gif)

**Comment by cezaryskura** [comment]
I think we can close that one (?)

**Comment by IAfanasovMob** [comment]
decided to use stripe instead of tikkie
